spring:
  servlet:
    multipart:
      # maximum of 25MB
      max-request-size: 25MB
      max-file-size: 25MB

# activate all debug logging
logging:
  level:
    de.phip1611: DEBUG

# activate actuator web endpoint
# SECURE THIS IN REVERSE PROXY
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      # activate health endpoints
      show-details: always

# this runs behind a reverse proxy
# always resolve forwarded headers
server:
  forward-headers-strategy: native

# RateLimitConfiguration.java
rate-limit:
  rate-limit-requests-per-interval: 1000 # 1000 requests per hour
  rate-limit-interval-seconds: 3600 # 1 hour = 60 minutes = 3600 seconds
