spring:
  servlet:
    multipart:
      # Bilder bis 25mb konvertieren
      max-request-size: 25MB
      max-file-size: 25MB
server:
  compression:
    enabled: true
    min-response-size: 100
    mime-types: application/json, text/html, text/css, application/javascript
