spring:
  servlet:
    multipart:
      # Bilder bis 25mb konvertieren
      max-request-size: 25MB
      max-file-size: 25MB
server:
  # alle anfragen von außen abblocken, das ist nur für andere (Spring) Services
  # auf dem gleichen Server gedacht
  address: "localhost"
  compression:
    enabled: true
    min-response-size: 100
    mime-types: application/json, text/html, text/css, application/javascript
