spring.profiles.active: test

spring:
  jpa:
    database: h2
    hibernate:
          ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:AZ
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
