spring:
  servlet:
    multipart:
      # Bilder bis 25mb konvertieren
      max-request-size: 25MB
server:
  # alle anfragen von außen abblocken, das ist nur für andere (Spring) Services
  # auf dem gleichen Server gedacht
  address: "localhost"
