name: Build

on: [ push, pull_request, merge_group ]

jobs:

  build_spring_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install webp converter
        run: sudo apt-get update && sudo apt-get install webp
      - name: Maven Build
        run: mvn --batch-mode --update-snapshots package
      - name: Unit Tests
        run: mvn --batch-mode --update-snapshots test
      - name: Integration Tests
        run: mvn --batch-mode --update-snapshots integration-test
      - name: Upload Web-App
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: img-to-webp-service/target

  build_docker:
    runs-on: ubuntu-latest
    needs: build_spring_app
    steps:
      - uses: actions/checkout@v4
      - name: Download Web-App from Previous Stage
        uses: actions/download-artifact@v3
        with:
          name: target
      - name: Install webp converter
        run: sudo apt-get update && sudo apt-get install webp
      - run: ./build-docker.sh
