name: Java/Maven CI

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install webp converter
        run: sudo apt-get update && sudo apt-get install webp
      - name: Maven Build
        run: mvn --batch-mode --update-snapshots package
      - name: Unit Tests
        run: mvn --batch-mode --update-snapshots test
      - name: Integration Tests
        run: mvn --batch-mode --update-snapshots integration-test